In [ ]:
import pandas as pd

jobs_df = pd.read_csv("/content/resume_job_matching_20000_jobs.csv", engine='python')

print("Dataset loaded successfully!")
print("Rows:", len(jobs_df))
print("Columns:", len(jobs_df.columns))

display(jobs_df.head())

Dataset loaded successfully!
Rows: 20000
Columns: 15

,job_id,job_title,company,source,location,job_type,experience_min,experience_max,salary_min,salary_max,skills,education,description,posted_date,job_url
0,1,Backend Developer,PwC,Naukri,"Gurgaon, India",Internship,4,7,1000000,2000000,"Python, Django, REST API, SQL, PostgreSQL, Git...",M.Sc,Backend Developer opportunity at PwC. Work on ...,2026-05-10,https://example.com/jobs/1
1,2,Software Engineer,Deloitte,Official Company Portal,"Noida, India",Contract,1,4,1000000,1500000,"Python, Java, C++, Data Structures, Algorithms...",B.Tech,Software Engineer opportunity at Deloitte. Wor...,2026-05-11,https://example.com/jobs/2
2,3,NLP Engineer,Accenture,Naukri,"Chennai, India",Full-time,1,2,400000,1400000,"Python, NLP, Transformers, BERT, Machine Learn...",M.E.,NLP Engineer opportunity at Accenture. Work on...,2026-07-18,https://example.com/jobs/3
3,4,Embedded Systems Engineer,Amazon,Naukri,"Jaipur, India",Contract,5,7,400000,1200000,"C, C++, Embedded Systems, Microcontrollers, CA...",B.E.,Embedded Systems Engineer opportunity at Amazo...,2026-02-13,https://example.com/jobs/4
4,5,Data Scientist,Google,Official Company Portal,"Ahmedabad, India",Contract,4,5,400000,1400000,"Python, Machine Learning, Statistics, SQL, Pan...",M.E.,Data Scientist opportunity at Google. Work on ...,2026-05-04,https://example.com/jobs/5

Upload your dataset to **Colab**

In [ ]:
print("Shape:")
print(jobs_df.shape)

print("\nColumns:")
print(jobs_df.columns.tolist())

print("\nData types:")
print(jobs_df.dtypes)

print("\nMissing values:")
display(jobs_df.isnull().sum())

Shape:
(20000, 15)

Columns:
['job_id', 'job_title', 'company', 'source', 'location', 'job_type', 'experience_min', 'experience_max', 'salary_min', 'salary_max', 'skills', 'education', 'description', 'posted_date', 'job_url']

Data types:
job_id             int64
job_title         object
company           object
source            object
location          object
job_type          object
experience_min     int64
experience_max     int64
salary_min         int64
salary_max         int64
skills            object
education         object
description       object
posted_date       object
job_url           object
dtype: object

Missing values:

job_id            0
job_title         0
company           0
source            0
location          0
job_type          0
experience_min    0
experience_max    0
salary_min        0
salary_max        0
skills            0
education         0
description       0
posted_date       0
job_url           0
dtype: int64

In [ ]:
# Remove duplicate job IDs
jobs_df = jobs_df.drop_duplicates(
    subset=["job_id"]
)

# Remove completely empty rows
jobs_df = jobs_df.dropna(
    how="all"
)

# Clean text columns
text_columns = [
    "job_title",
    "company",
    "source",
    "location",
    "job_type",
    "skills",
    "education",
    "description",
    "job_url"
]

for col in text_columns:
    jobs_df[col] = (
        jobs_df[col]
        .fillna("")
        .astype(str)
        .str.strip()
    )

# Convert date
jobs_df["posted_date"] = pd.to_datetime(
    jobs_df["posted_date"],
    errors="coerce"
)

print("Cleaning completed.")
print("Rows remaining:", len(jobs_df))

Cleaning completed.
Rows remaining: 20000

In [ ]:
print(
    "Duplicate job IDs:",
    jobs_df["job_id"].duplicated().sum()
)

print(
    "Duplicate job titles:",
    jobs_df["job_title"].duplicated().sum()
)

print(
    "Duplicate descriptions:",
    jobs_df["description"].duplicated().sum()
)

Duplicate job IDs: 0
Duplicate job titles: 19980
Duplicate descriptions: 19120

In [ ]:
company_counts = (
    jobs_df["company"]
    .value_counts()
    .head(20)
)

display(company_counts)
source_counts = (
    jobs_df["source"]
    .value_counts()
)

display(source_counts)
role_counts = (
    jobs_df["job_title"]
    .value_counts()
    .head(20)
)

display(role_counts)
location_counts = (
    jobs_df["location"]
    .value_counts()
    .head(20)
)

display(location_counts)

company
Ford              491
Volvo             489
EY                487
ZF                485
JPMorgan Chase    484
Tata Motors       483
BMW               482
Continental       480
Google            479
Capgemini         474
SAP               470
Siemens           468
Adobe             468
Wells Fargo       468
Mahindra          468
Deloitte          465
KPMG              464
General Motors    462
Microsoft         458
IBM               457
Name: count, dtype: int64

source
Naukri                     5068
Official Company Portal    5020
Company Careers            4966
LinkedIn                   4946
Name: count, dtype: int64

job_title
Data Scientist                  1064
Product Manager                 1052
Automotive Software Engineer    1044
Electrical Engineer             1042
Database Administrator          1024
Frontend Developer              1019
Full Stack Developer            1015
Cybersecurity Analyst           1013
Business Analyst                1004
Embedded Systems Engineer        995
AI Engineer                      991
Data Analyst                     990
Mechanical Engineer              985
NLP Engineer                     984
DevOps Engineer                  978
QA Engineer                      975
Cloud Engineer                   968
Backend Developer                965
Software Engineer                946
Machine Learning Engineer        946
Name: count, dtype: int64

location
Remote, India        1502
Ahmedabad, India     1475
Hyderabad, India     1468
Mumbai, India        1457
Bangalore, India     1442
Gurgaon, India       1427
Delhi, India         1425
Chennai, India       1424
Noida, India         1416
Jaipur, India        1415
Kolkata, India       1410
Coimbatore, India    1396
Pune, India          1383
Mysore, India        1360
Name: count, dtype: int64

In [ ]:
cleaned_file = "jobs_cleaned_20000.csv"

jobs_df.to_csv(
    cleaned_file,
    index=False
)

print("Saved:", cleaned_file)

Saved: jobs_cleaned_20000.csv

In [ ]:
from google.colab import files
files.download(cleaned_file)

In [ ]:
!pip -q install mysql-connector-python

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.7/21.7 MB 91.5 MB/s eta 0:00:00

In [ ]:
!pip install -q pymupdf python-docx pandas numpy scikit-learn mysql-connector-python gradio

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.8/25.8 MB 44.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 253.0/253.0 kB 14.2 MB/s eta 0:00:00

In [ ]:
import pandas as pd
import numpy as np

cleaned_file = "jobs_cleaned_20000.csv"

try:
    # Try to read the cleaned file first
    jobs_df = pd.read_csv(cleaned_file)
    print(f"Successfully loaded '{cleaned_file}'.")
except FileNotFoundError:
    print(f"'{cleaned_file}' not found. Attempting to re-create it from the original data.")
    # If the cleaned file is not found, load the original data and clean it.
    # This assumes the original file path is known and accessible.
    original_file = "/content/resume_job_matching_20000_jobs.csv" # Path from cell tUNtkgq0YKiM
    try:
        jobs_df = pd.read_csv(original_file)

        # Apply cleaning steps from cell rPvP7wh8ZDCl
        jobs_df = jobs_df.drop_duplicates(subset=["job_id"])
        jobs_df = jobs_df.dropna(how="all")
        text_columns = ["job_title", "company", "source", "location", "job_type", "skills", "education", "description", "job_url"]
        for col in text_columns:
            jobs_df[col] = jobs_df[col].fillna("").astype(str).str.strip()
        jobs_df["posted_date"] = pd.to_datetime(jobs_df["posted_date"], errors="coerce")

        # Save the cleaned DataFrame
        jobs_df.to_csv(cleaned_file, index=False)
        print(f"Successfully re-created and saved '{cleaned_file}'.")

    except FileNotFoundError:
        print(f"Error: Original file '{original_file}' also not found. Please ensure the dataset is uploaded or the path is correct.")
        raise # Re-raise the FileNotFoundError if original is also missing
    except Exception as e:
        print(f"An unexpected error occurred during recreation: {e}")
        raise

print("Dataset loaded successfully!")
print("Number of jobs:", len(jobs_df))
print("Number of columns:", len(jobs_df.columns))

display(jobs_df.head())

Successfully loaded 'jobs_cleaned_20000.csv'.
Dataset loaded successfully!
Number of jobs: 20000
Number of columns: 15

,job_id,job_title,company,source,location,job_type,experience_min,experience_max,salary_min,salary_max,skills,education,description,posted_date,job_url
0,1,Backend Developer,PwC,Naukri,"Gurgaon, India",Internship,4,7,1000000,2000000,"Python, Django, REST API, SQL, PostgreSQL, Git...",M.Sc,Backend Developer opportunity at PwC. Work on ...,2026-05-10,https://example.com/jobs/1
1,2,Software Engineer,Deloitte,Official Company Portal,"Noida, India",Contract,1,4,1000000,1500000,"Python, Java, C++, Data Structures, Algorithms...",B.Tech,Software Engineer opportunity at Deloitte. Wor...,2026-05-11,https://example.com/jobs/2
2,3,NLP Engineer,Accenture,Naukri,"Chennai, India",Full-time,1,2,400000,1400000,"Python, NLP, Transformers, BERT, Machine Learn...",M.E.,NLP Engineer opportunity at Accenture. Work on...,2026-07-18,https://example.com/jobs/3
3,4,Embedded Systems Engineer,Amazon,Naukri,"Jaipur, India",Contract,5,7,400000,1200000,"C, C++, Embedded Systems, Microcontrollers, CA...",B.E.,Embedded Systems Engineer opportunity at Amazo...,2026-02-13,https://example.com/jobs/4
4,5,Data Scientist,Google,Official Company Portal,"Ahmedabad, India",Contract,4,5,400000,1400000,"Python, Machine Learning, Statistics, SQL, Pan...",M.E.,Data Scientist opportunity at Google. Work on ...,2026-05-04,https://example.com/jobs/5

In [ ]:
print(jobs_df.columns.tolist())

['job_id', 'job_title', 'company', 'source', 'location', 'job_type', 'experience_min', 'experience_max', 'salary_min', 'salary_max', 'skills', 'education', 'description', 'posted_date', 'job_url']

In [ ]:
import os
import re
import pandas as pd
import numpy as np

!pip install -q PyMuPDF
import fitz # PyMuPDF library
!pip install -q python-docx
from docx import Document

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

import gradio as gr

warning: The `fitz` API is deprecated and will be removed in future. Use `import pymupdf` instead.

In [ ]:
jobs_df["job_text"] = (
    jobs_df["job_title"].fillna("").astype(str) + " " +
    jobs_df["skills"].fillna("").astype(str) + " " +
    jobs_df["education"].fillna("").astype(str) + " " +
    jobs_df["description"].fillna("").astype(str)
)

print("Job text created successfully.")

Job text created successfully.

In [ ]:
tfidf = TfidfVectorizer(
    stop_words="english",
    lowercase=True,
    ngram_range=(1, 2),
    max_features=20000
)

job_vectors = tfidf.fit_transform(
    jobs_df["job_text"]
)

print("TF-IDF completed.")
print("Matrix shape:", job_vectors.shape)

TF-IDF completed.
Matrix shape: (20000, 932)

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving Suhas.M.Gomadi-Resume.pdf to Suhas.M.Gomadi-Resume.pdf

In [ ]:
resume_filename = list(uploaded.keys())[0]

print("Uploaded:", resume_filename)

Uploaded: Suhas.M.Gomadi-Resume.pdf

In [ ]:
def extract_pdf_text(file_path):

    text = ""

    document = fitz.open(file_path)

    for page in document:
        text += page.get_text()

    document.close()

    return text

In [ ]:
resume_text = extract_pdf_text(
    resume_filename
)

print(resume_text[:5000])

SUHAS M GOMADI
Electronics & Communication Engineering Bengaluru, Karnataka, India
suhasmgomadi@gmail.com | Phone: 6366668691 | LinkedIn: linkedin.com/in/suhas-m-gomadi-55b273312
OBJECTIVE
Electronics and Communication Engineering undergraduate (expected 2027) with hands-on experience in
embedded systems, IoT, and hardware-software integration. Built a Smart Rescue Robot for disaster zones,
handling robot assembly, circuit design, and embedded integration. Backed by coursework and certifications in
microcontrollers, C++, and AI fundamentals. Strong communicator and quick learner seeking an embedded
systems or engineering trainee role.
EDUCATION
Bachelor of Engineering - Electronics & Communication Engineering | Expected Graduation: 2027 | CGPA: 8.18
PUC - New National PU College, Bengaluru | 2023 | 84.16%
SSLC - New Balaji Vikram English High School, Bengaluru | 2021 | 80.8%
ACADEMIC PROJECTS
Smart Rescue Robot for Disaster Zones   |   Aug 2025 - Nov 2025
• Designed and assembled a rescue robot for disaster-zone navigation using embedded systems and IoT
modules.
• Handled circuit integration between sensors, microcontroller, and communication modules for real-time
operation.
Portable Oil Extracting Machine | Currently Working
• Designing and developing an automated oil extraction machine using an 8051 microcontroller to control a
motor-driven mechanism, integrating temperature, pressure, load cell, and speed sensors for real-time
monitoring and fault detection.
• Building embedded control logic in Embedded C using Keil µVision, validating circuit design through Proteus
simulation, and implementing actuator control with an LCD display and keypad-based interface.
TECHNICAL SKILLS
Languages: C++(basics), Python
Tools: Matlab(Simulink), Cadence, PowerPoint, Jupyter Notebook
Domain: Embedded Systems, Microcontrollers, IoT
Strengths: Communication, Teamwork, Time Management, Quick Learner
CERTIFICATIONS & TRAINING
• Electronics Course - Infosys Springboard, Apr 2025
• Microprocessor and Microcontroller - NPTEL, May 2025
• C++ Programming Advanced Certification - TechA, Dec 2025
• Artificial Intelligence Fundamentals - IBM Skills Build, Jul 2026
• Cyber Job Simulation – Deloitte, July 2026
EXTRA CURRICULARS
Part of events in Electronica forum also acted as coordinator made reports of the events.
Class Representative managed events and played a major role in various class activities like AICTE activities.

In [ ]:
SKILLS = [
    "python",
    "java",
    "c++",
    "c#",
    "javascript",
    "typescript",
    "sql",
    "mysql",
    "postgresql",
    "mongodb",
    "oracle",
    "excel",
    "power bi",
    "tableau",
    "machine learning",
    "deep learning",
    "artificial intelligence",
    "data science",
    "data analysis",
    "statistics",
    "pandas",
    "numpy",
    "scikit-learn",
    "tensorflow",
    "pytorch",
    "nlp",
    "natural language processing",
    "html",
    "css",
    "react",
    "angular",
    "node.js",
    "django",
    "flask",
    "fastapi",
    "rest api",
    "git",
    "github",
    "docker",
    "kubernetes",
    "linux",
    "aws",
    "azure",
    "gcp",
    "matlab",
    "simulink",
    "autocad",
    "solidworks",
    "cad",
    "embedded systems",
    "microcontrollers",
    "automotive",
    "agile",
    "scrum",
    "jira",
    "selenium"
]

In [ ]:
def extract_skills(text):
    found_skills = []
    text_lower = text.lower()
    for skill in SKILLS:
        # Use a regex to find the skill as a whole word
        if re.search(r'\b' + re.escape(skill) + r'\b', text_lower):
            found_skills.append(skill)
    return found_skills

resume_skills = extract_skills(resume_text)

print("Detected Skills:")
for skill in resume_skills:
    print("✓", skill)

Detected Skills:
✓ python
✓ artificial intelligence
✓ matlab
✓ simulink
✓ embedded systems
✓ microcontrollers

In [ ]:
DEGREE_PATTERNS = {

    "B.Tech": [
        r"\bb\.?\s*tech\b",
        r"\bbtech\b",
        r"\bbachelor of technology\b"
    ],

    "B.E.": [
        r"\bb\.?\s*e\.?\b",
        r"\bbe\b",
        r"\bbachelor of engineering\b"
    ],

    "M.Tech": [
        r"\bm\.?\s*tech\b",
        r"\bmtech\b",
        r"\bmaster of technology\b"
    ],

    "M.E.": [
        r"\bm\.?\s*e\.?\b",
        r"\bme\b",
        r"\bmaster of engineering\b"
    ],

    "BCA": [
        r"\bbca\b",
        r"\bbachelor of computer applications\b"
    ],

    "MCA": [
        r"\bmca\b",
        r"\bmaster of computer applications\b"
    ],

    "B.Sc": [
        r"\bb\.?\s*sc\b",
        r"\bbachelor of science\b"
    ],

    "M.Sc": [
        r"\bm\.?\s*sc\b",
        r"\bmaster of science\b"
    ],

    "MBA": [
        r"\bmba\b",
        r"\bmaster of business administration\b"
    ],

    "PhD": [
        r"\bph\.?\s*d\b",
        r"\bdoctor of philosophy\b"
    ]
}

In [ ]:
def extract_degrees(text):

    text = text.lower()

    degrees = []

    for degree, patterns in DEGREE_PATTERNS.items():

        for pattern in patterns:

            if re.search(pattern, text):
                degrees.append(degree)
                break

    return sorted(set(degrees))

In [ ]:
resume_degrees = extract_degrees(resume_text)

print("Education:")
print(resume_degrees)

Education:
['B.E.']

In [ ]:
BRANCHES = [
    "computer science",
    "computer science engineering",
    "information technology",
    "information science",
    "artificial intelligence",
    "artificial intelligence and machine learning",
    "data science",
    "electronics",
    "electronics and communication",
    "electrical engineering",
    "mechanical engineering",
    "civil engineering",
    "automobile engineering",
    "mechatronics",
    "chemical engineering"
]

In [ ]:
def extract_branches(text):

    text = text.lower()

    branches = []

    for branch in BRANCHES:

        if branch in text:
            branches.append(branch)

    return sorted(set(branches))

In [ ]:
resume_branches = extract_branches(resume_text)

print("Specialization:")
print(resume_branches)

Specialization:
['artificial intelligence', 'electronics', 'electronics and communication']

In [ ]:
def extract_experience(text):

    text = text.lower()

    patterns = [
        r"(\d+)\+?\s*years?\s*(?:of)?\s*experience",
        r"(\d+)\+?\s*years?\s*work experience",
        r"experience\s*[:\-]?\s*(\d+)\+?\s*years?"
    ]

    values = []

    for pattern in patterns:

        matches = re.findall(
            pattern,
            text
        )

        for value in matches:

            try:
                values.append(int(value))
            except:
                pass

    if values:
        return max(values)

    return 0

In [ ]:
experience = extract_experience(
    resume_text
)

print("Experience:", experience, "years")

Experience: 0 years

In [ ]:
def identify_profile(skills):

    skill_set = set(
        skill.lower()
        for skill in skills
    )

    if {"machine learning", "python"}.issubset(skill_set):
        return "Machine Learning / AI"

    if {"data science", "python"}.issubset(skill_set):
        return "Data Science"

    if {"nlp", "python"}.issubset(skill_set):
        return "NLP / AI"

    if {"react", "javascript"}.issubset(skill_set):
        return "Frontend Development"

    if {"django", "python"}.issubset(skill_set):
        return "Backend Development"

    if {"sql", "power bi"}.issubset(skill_set):
        return "Data Analytics"

    if {"c++", "embedded systems"}.issubset(skill_set):
        return "Embedded Systems"

    return "Software / Technology"

In [ ]:
profile = identify_profile(
    resume_skills
)

print("Detected Profile:", profile)

Detected Profile: Software / Technology

In [ ]:
resume_vector = tfidf.transform(
    [resume_text]
)

In [ ]:
similarities = cosine_similarity(
    resume_vector,
    job_vectors
).flatten()

In [ ]:
jobs_df["similarity_score"] = (
    similarities * 100
)

In [ ]:
top_jobs = jobs_df.sort_values(
    "similarity_score",
    ascending=False
).head(10)

In [ ]:
display(
    top_jobs[
        [
            "job_title",
            "company",
            "source",
            "location",
            "similarity_score"
        ]
    ]
)

,job_title,company,source,location,similarity_score
13873,Embedded Systems Engineer,Infosys,Official Company Portal,"Mysore, India",58.668170
3551,Embedded Systems Engineer,Infosys,Naukri,"Bangalore, India",58.668170
2053,Embedded Systems Engineer,Infosys,Official Company Portal,"Bangalore, India",58.668170
16836,Embedded Systems Engineer,Infosys,LinkedIn,"Hyderabad, India",58.668170
18546,Embedded Systems Engineer,IBM,LinkedIn,"Coimbatore, India",57.709864
9913,Embedded Systems Engineer,Deloitte,Company Careers,"Remote, India",57.599172
19157,Embedded Systems Engineer,Infosys,LinkedIn,"Chennai, India",57.565038
18927,Embedded Systems Engineer,Deloitte,LinkedIn,"Noida, India",57.372315
1770,Embedded Systems Engineer,Deloitte,Company Careers,"Hyderabad, India",57.372315
3645,Embedded Systems Engineer,IBM,Official Company Portal,"Pune, India",57.370755

In [ ]:
print("Top 10 jobs based on TF-IDF similarity:")

display(
    top_jobs[
        [
            "job_title",
            "company",
            "source",
            "location",
            "experience_min",
            "experience_max",
            "education",
            "skills",
            "similarity_score"
        ]
    ]
)

Top 10 jobs based on TF-IDF similarity:

,job_title,company,source,location,experience_min,experience_max,education,skills,similarity_score
13873,Embedded Systems Engineer,Infosys,Official Company Portal,"Mysore, India",0,2,B.E.,"C, C++, Embedded Systems, Microcontrollers, CA...",58.668170
3551,Embedded Systems Engineer,Infosys,Naukri,"Bangalore, India",1,2,B.E.,"C, C++, Embedded Systems, Microcontrollers, CA...",58.668170
2053,Embedded Systems Engineer,Infosys,Official Company Portal,"Bangalore, India",1,3,B.E.,"C, C++, Embedded Systems, Microcontrollers, CA...",58.668170
16836,Embedded Systems Engineer,Infosys,LinkedIn,"Hyderabad, India",0,3,M.E.,"C, C++, Embedded Systems, Microcontrollers, CA...",58.668170
18546,Embedded Systems Engineer,IBM,LinkedIn,"Coimbatore, India",3,6,B.E.,"C, C++, Embedded Systems, Microcontrollers, CA...",57.709864
9913,Embedded Systems Engineer,Deloitte,Company Careers,"Remote, India",3,4,B.Tech,"C, C++, Embedded Systems, Microcontrollers, CA...",57.599172
19157,Embedded Systems Engineer,Infosys,LinkedIn,"Chennai, India",3,4,B.Sc,"C, C++, Embedded Systems, Microcontrollers, CA...",57.565038
18927,Embedded Systems Engineer,Deloitte,LinkedIn,"Noida, India",5,7,M.Tech,"C, C++, Embedded Systems, Microcontrollers, CA...",57.372315
1770,Embedded Systems Engineer,Deloitte,Company Careers,"Hyderabad, India",0,3,B.Tech,"C, C++, Embedded Systems, Microcontrollers, CA...",57.372315
3645,Embedded Systems Engineer,IBM,Official Company Portal,"Pune, India",4,6,M.Tech,"C, C++, Embedded Systems, Microcontrollers, CA...",57.370755

In [ ]:
def calculate_skill_match(resume_skills, job_skills):

    resume_set = set(
        str(skill).lower().strip()
        for skill in resume_skills
    )

    job_set = set(
        skill.strip().lower()
        for skill in str(job_skills).split(",")
        if skill.strip()
    )

    if len(job_set) == 0:
        return 0, [], []

    matched = sorted(
        resume_set.intersection(job_set)
    )

    missing = sorted(
        job_set.difference(resume_set)
    )

    score = (
        len(matched) / len(job_set)
    ) * 100

    return score, matched, missing

In [ ]:
def calculate_education_match(
    resume_degrees,
    job_education
):

    if not resume_degrees:
        return 50

    job_education = str(
        job_education
    ).lower()

    if "any" in job_education:
        return 100

    for degree in resume_degrees:

        degree = degree.lower()

        if degree in job_education:
            return 100

        # Flexible matching
        if degree == "b.tech" and (
            "btech" in job_education or
            "b.tech" in job_education
        ):
            return 100

        if degree == "m.tech" and (
            "mtech" in job_education or
            "m.tech" in job_education
        ):
            return 100

    return 40

In [ ]:
def calculate_experience_match(
    resume_experience,
    minimum_experience,
    maximum_experience
):

    try:
        resume_experience = float(
            resume_experience
        )

        minimum_experience = float(
            minimum_experience
        )

        maximum_experience = float(
            maximum_experience
        )

    except:
        return 50

    # Perfect range
    if (
        minimum_experience
        <= resume_experience
        <= maximum_experience
    ):
        return 100

    # Candidate has slightly less experience
    if resume_experience < minimum_experience:

        difference = (
            minimum_experience
            - resume_experience
        )

        if difference <= 1:
            return 75

        if difference <= 2:
            return 50

        return 25

    # Candidate has more experience
    if resume_experience > maximum_experience:
        return 90

    return 50

In [ ]:
def generate_job_recommendations(
    resume_text,
    top_n=10
):

    # -----------------------------
    # Analyze resume
    # -----------------------------

    resume_skills = extract_skills(
        resume_text
    )

    resume_degrees = extract_degrees(
        resume_text
    )

    resume_branches = extract_branches(
        resume_text
    )

    resume_experience = extract_experience(
        resume_text
    )

    resume_profile = identify_profile(
        resume_skills
    )

    # -----------------------------
    # TF-IDF similarity
    # -----------------------------

    resume_vector = tfidf.transform(
        [resume_text]
    )

    similarities = cosine_similarity(
        resume_vector,
        job_vectors
    ).flatten()

    results = []

    # -----------------------------
    # Score every job
    # -----------------------------

    for i, job in jobs_df.iterrows():

        tfidf_score = (
            similarities[i] * 100
        )

        skill_score, matched_skills, missing_skills = (
            calculate_skill_match(
                resume_skills,
                job["skills"]
            )
        )

        education_score = (
            calculate_education_match(
                resume_degrees,
                job["education"]
            )
        )

        experience_score = (
            calculate_experience_match(
                resume_experience,
                job["experience_min"],
                job["experience_max"]
            )
        )

        # -----------------------------
        # Final weighted score
        # -----------------------------

        final_score = (
            0.50 * tfidf_score +
            0.30 * skill_score +
            0.10 * education_score +
            0.10 * experience_score
        )

        results.append({

            "Job Title":
                job["job_title"],

            "Company":
                job["company"],

            "Source":
                job["source"],

            "Location":
                job["location"],

            "Education":
                job["education"],

            "Experience":
                str(job["experience_min"])
                + " - "
                + str(job["experience_max"])
                + " years",

            "Match Score":
                round(final_score, 2),

            "TF-IDF Score":
                round(tfidf_score, 2),

            "Skill Score":
                round(skill_score, 2),

            "Matched Skills":
                ", ".join(matched_skills),

            "Missing Skills":
                ", ".join(missing_skills),

            "Job URL":
                job["job_url"]

        })

    results_df = pd.DataFrame(
        results
    )

    results_df = results_df.sort_values(
        "Match Score",
        ascending=False
    )

    return {
        "profile": resume_profile,
        "skills": resume_skills,
        "degrees": resume_degrees,
        "branches": resume_branches,
        "experience": resume_experience,
        "recommendations": results_df.head(top_n)
    }

In [ ]:
results = generate_job_recommendations(
    resume_text,
    top_n=10
)

In [ ]:
print("PROFILE:")
print(results["profile"])

print("\nSKILLS:")
print(", ".join(results["skills"]))

print("\nDEGREES:")
print(", ".join(results["degrees"]))

print("\nBRANCH:")
print(", ".join(results["branches"]))

print("\nEXPERIENCE:")
print(results["experience"], "years")

PROFILE:
Software / Technology

SKILLS:
python, artificial intelligence, matlab, simulink, embedded systems, microcontrollers

DEGREES:
B.E.

BRANCH:
artificial intelligence, electronics, electronics and communication

EXPERIENCE:
0 years

In [ ]:
display(
    results["recommendations"]
)

,Job Title,Company,Source,Location,Education,Experience,Match Score,TF-IDF Score,Skill Score,Matched Skills,Missing Skills,Job URL
13645,Embedded Systems Engineer,ZF,Naukri,"Delhi, India",B.E.,0 - 3 years,60.68,55.64,42.86,"embedded systems, microcontrollers, python","automotive, c, c++, can",https://example.com/jobs/13646
13873,Embedded Systems Engineer,Infosys,Official Company Portal,"Mysore, India",B.E.,0 - 2 years,59.33,58.67,33.33,"embedded systems, microcontrollers","automotive, c, c++, can",https://example.com/jobs/13874
17839,Embedded Systems Engineer,Honeywell,LinkedIn,"Bangalore, India",Any Bachelor's Degree,0 - 3 years,58.58,54.65,37.50,"embedded systems, microcontrollers, python","automotive, c, c++, can, sql",https://example.com/jobs/17840
19051,Embedded Systems Engineer,Flipkart,LinkedIn,"Mysore, India",B.E.,0 - 1 years,58.33,54.16,37.50,"embedded systems, microcontrollers, python","automotive, c, c++, can, linux",https://example.com/jobs/19052
5484,Embedded Systems Engineer,EY,Company Careers,"Gurgaon, India",B.E.,0 - 1 years,58.29,56.57,33.33,"embedded systems, microcontrollers","automotive, c, c++, can",https://example.com/jobs/5485
4816,Embedded Systems Engineer,EY,Company Careers,"Mysore, India",B.E.,0 - 3 years,58.29,56.57,33.33,"embedded systems, microcontrollers","automotive, c, c++, can",https://example.com/jobs/4817
12541,Embedded Systems Engineer,Ford,Official Company Portal,"Ahmedabad, India",B.E.,0 - 3 years,58.29,56.58,33.33,"embedded systems, microcontrollers","automotive, c, c++, can",https://example.com/jobs/12542
17937,Embedded Systems Engineer,Google,Official Company Portal,"Mumbai, India",B.E.,0 - 2 years,58.28,56.56,33.33,"embedded systems, microcontrollers","automotive, c, c++, can",https://example.com/jobs/17938
11568,Embedded Systems Engineer,Capgemini,Company Careers,"Bangalore, India",B.E.,0 - 3 years,58.27,56.55,33.33,"embedded systems, microcontrollers","automotive, c, c++, can",https://example.com/jobs/11569
16154,Embedded Systems Engineer,Hyundai,LinkedIn,"Remote, India",B.E.,0 - 2 years,58.25,56.49,33.33,"embedded systems, microcontrollers","automotive, c, c++, can",https://example.com/jobs/16155

In [ ]:
from google.colab import files

uploaded_resume = files.upload()

resume_filename = list(
    uploaded_resume.keys()
)[0]

print(
    "Resume uploaded:",
    resume_filename
)

Saving Suhas.M.Gomadi-Resume.pdf to Suhas.M.Gomadi-Resume (1).pdf
Resume uploaded: Suhas.M.Gomadi-Resume (1).pdf

In [ ]:
resume_text = extract_pdf_text(
    resume_filename
)

print(
    resume_text[:3000]
)

SUHAS M GOMADI
Electronics & Communication Engineering Bengaluru, Karnataka, India
suhasmgomadi@gmail.com | Phone: 6366668691 | LinkedIn: linkedin.com/in/suhas-m-gomadi-55b273312
OBJECTIVE
Electronics and Communication Engineering undergraduate (expected 2027) with hands-on experience in
embedded systems, IoT, and hardware-software integration. Built a Smart Rescue Robot for disaster zones,
handling robot assembly, circuit design, and embedded integration. Backed by coursework and certifications in
microcontrollers, C++, and AI fundamentals. Strong communicator and quick learner seeking an embedded
systems or engineering trainee role.
EDUCATION
Bachelor of Engineering - Electronics & Communication Engineering | Expected Graduation: 2027 | CGPA: 8.18
PUC - New National PU College, Bengaluru | 2023 | 84.16%
SSLC - New Balaji Vikram English High School, Bengaluru | 2021 | 80.8%
ACADEMIC PROJECTS
Smart Rescue Robot for Disaster Zones   |   Aug 2025 - Nov 2025
• Designed and assembled a rescue robot for disaster-zone navigation using embedded systems and IoT
modules.
• Handled circuit integration between sensors, microcontroller, and communication modules for real-time
operation.
Portable Oil Extracting Machine | Currently Working
• Designing and developing an automated oil extraction machine using an 8051 microcontroller to control a
motor-driven mechanism, integrating temperature, pressure, load cell, and speed sensors for real-time
monitoring and fault detection.
• Building embedded control logic in Embedded C using Keil µVision, validating circuit design through Proteus
simulation, and implementing actuator control with an LCD display and keypad-based interface.
TECHNICAL SKILLS
Languages: C++(basics), Python
Tools: Matlab(Simulink), Cadence, PowerPoint, Jupyter Notebook
Domain: Embedded Systems, Microcontrollers, IoT
Strengths: Communication, Teamwork, Time Management, Quick Learner
CERTIFICATIONS & TRAINING
• Electronics Course - Infosys Springboard, Apr 2025
• Microprocessor and Microcontroller - NPTEL, May 2025
• C++ Programming Advanced Certification - TechA, Dec 2025
• Artificial Intelligence Fundamentals - IBM Skills Build, Jul 2026
• Cyber Job Simulation – Deloitte, July 2026
EXTRA CURRICULARS
Part of events in Electronica forum also acted as coordinator made reports of the events.
Class Representative managed events and played a major role in various class activities like AICTE activities.

In [ ]:
def process_resume(file):

    if file is None:

        return (
            "Please upload a resume.",
            "",
            "",
            "",
            "",
            "",
            pd.DataFrame()
        )

    try:

        file_path = file.name

        # -------------------------
        # Extract text
        # -------------------------

        if file_path.lower().endswith(".pdf"):

            text = extract_pdf_text(
                file_path
            )

        elif file_path.lower().endswith(".docx"):

            text = extract_docx_text(
                file_path
            )

        elif file_path.lower().endswith(".txt"):

            with open(
                file_path,
                "r",
                encoding="utf-8"
            ) as f:

                text = f.read()

        else:

            return (
                "Unsupported file type.",
                "",
                "",
                "",
                "",
                "",
                pd.DataFrame()
            )

        # -------------------------
        # Run recommendation engine
        # -------------------------

        results = generate_job_recommendations(
            text,
            top_n=10
        )

        profile = results["profile"]

        skills = ", ".join(
            results["skills"]
        )

        degrees = ", ".join(
            results["degrees"]
        )

        branches = ", ".join(
            results["branches"]
        )

        experience = (
            str(results["experience"])
            + " years"
        )

        recommendations = (
            results["recommendations"]
        )

        return (
            "Resume analyzed successfully!",
            profile,
            skills,
            degrees,
            branches,
            experience,
            recommendations
        )

    except Exception as e:

        return (
            "Error: " + str(e),
            "",
            "",
            "",
            "",
            "",
            pd.DataFrame()
        )

In [ ]:
with gr.Blocks(
    title="AI Resume Screening & Job Matching"
) as app:

    gr.Markdown(
        """
        # AI Resume Screening & Job Matching System

        Upload your resume and the system will identify
        your profile, skills, education and experience,
        then recommend relevant jobs from the dataset.
        """
    )

    gr.Markdown(
        "## 1. Upload Your Resume"
    )

    resume_upload = gr.File(
        label="Upload Resume",
        file_types=[
            ".pdf",
            ".docx",
            ".txt"
        ],
        type="filepath"
    )

    analyze_button = gr.Button(
        "Analyze Resume & Find Jobs",
        variant="primary"
    )

    status = gr.Textbox(
        label="Status"
    )

    gr.Markdown(
        "## 2. Candidate Profile"
    )

    profile = gr.Textbox(
        label="Detected Profile"
    )

    skills = gr.Textbox(
        label="Detected Skills",
        lines=3
    )

    degree = gr.Textbox(
        label="Detected Education"
    )

    branch = gr.Textbox(
        label="Detected Branch / Specialization"
    )

    experience = gr.Textbox(
        label="Detected Experience"
    )

    gr.Markdown(
        "## 3. Recommended Jobs"
    )

    recommendations = gr.Dataframe(
        label="Top 10 Recommended Jobs",
        interactive=False,
        wrap=True
    )

    analyze_button.click(
        fn=process_resume,
        inputs=resume_upload,
        outputs=[
            status,
            profile,
            skills,
            degree,
            branch,
            experience,
            recommendations
        ]
    )

app.launch(
    share=True,
    debug=True
)

Colab notebook detected. This cell will run indefinitely so that you can see errors and logs. To turn off, set debug=False in launch().
* Running on public URL: https://d2848aa4475f7e6819.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)